version: "3.9"

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydb
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "28017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
